Initial PDP version.
memoryz/mmlspark pull request #1
Opened 2021-09-17 18:11 UTC by ezherdeva

2021-09-17 19:50 UTC, memoryz requested changes

2021-09-23 22:27 UTC, ezherdeva commented on core/src/main/scala/com/microsoft/ml/spark/explainers/ICEExplainer.scala
> +          val mi = rangeMin.map(_.toLong).getOrElse(minValue)
Do we need `getOrElse` here? Because we enter this branch if the ranges aren't defined.

2021-09-28 23:04 UTC, memoryz commented on core/src/main/scala/com/microsoft/ml/spark/explainers/ICEExplainer.scala
> +    "topNValues",
Please write more detailed doc string.

2021-10-08 19:52 UTC, memoryz requested changes

2021-10-08 19:52 UTC, memoryz commented on core/src/main/scala/com/microsoft/ml/spark/explainers/ICEExplainer.scala
> +    val sampled = dfWithId.orderBy(rand()).limit(getNumSamples).cache()
Add some logic here: if numSamples is set to -1, then don't sample.

2021-10-08 19:52 UTC, memoryz commented on core/src/main/scala/com/microsoft/ml/spark/explainers/ICEExplainer.scala
> +        sampled.join(iceFeatures, idCol)
Please specify the join type to be "inner". Also drop the idCol after the join.

2021-10-08 19:52 UTC, memoryz commented on core/src/main/scala/com/microsoft/ml/spark/explainers/ICEExplainer.scala
>              .select("__feature__name__", "__feature__value__", "__feature__importance__")
Thinking about the schema here. For PDP, it returns ["__feature__name__", "__feature__value__", "__feature__importance__"]. For ICE, it returns a new "__feature__importance__" column in addition to input columns. But the schema for "__feature__importance__" is different in the two cases. Maybe unify the PDP schema to just one "__feature__importance__" column?

2021-10-08 19:52 UTC, memoryz commented on core/src/test/scala/com/microsoft/ml/spark/explainers/split1/ICEExplainerSuite.scala
> +  data.show()
Remove the "show". It will clutter test log.

2021-10-08 19:52 UTC, memoryz commented on core/src/test/scala/com/microsoft/ml/spark/explainers/split1/ICEExplainerSuite.scala
> +  output.show(false)
where are the asserts?

2021-10-08 19:52 UTC, memoryz commented on core/src/main/scala/com/microsoft/ml/spark/explainers/ICEExplainer.scala
> +  def setContinuousFeature(feature: String, nSplits: Int,
Can you also create a setDiscreteFeature function?

2021-11-16 19:20 UTC, memoryz requested changes
Overall looks good. Please add more code documentation, and more test cases.

2021-11-16 19:20 UTC, memoryz commented on core/src/main/scala/com/microsoft/azure/synapse/ml/explainers/ICEExplainer.scala
> +        )
Drop the `idCol` after the final join. Also specify the join type to be "inner" for the last join.

2021-11-16 19:20 UTC, memoryz commented on core/src/main/scala/com/microsoft/azure/synapse/ml/explainers/ICEExplainer.scala
> +            "Call setCategoricalFeatures or setNumericFeatures to set the features to be explained.")
Extract the error string to a local variable to reduce duplication.

2021-11-16 19:20 UTC, memoryz commented on core/src/main/scala/com/microsoft/azure/synapse/ml/explainers/ICEExplainer.scala
> +      .agg(count("*").as("__feature__count__"))
Use DatasetExtensions.findUnusedColumnName to find a column name rather than hard code the name here.

2021-11-16 19:20 UTC, memoryz commented on core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/ICEExplainerSuite.scala
> +
Remove empty lines.

2021-11-16 19:20 UTC, memoryz commented on core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/ICEExplainerSuite.scala
> +class ICEExplainerSuite extends TestBase {// with TransformerFuzzing[ICETransformer] {
Add back TransformerFuzzing

2021-11-16 19:20 UTC, memoryz commented on core/src/main/scala/com/microsoft/azure/synapse/ml/explainers/ICEExplainer.scala
> +  override def transformSchema(schema: StructType): StructType = {
Check that if no feature is specified, an error should be thrown. This makes sure the error is thrown early.

2021-11-16 19:20 UTC, memoryz commented on core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/ICEExplainerSuite.scala
> +class ICEExplainerSuite extends TestBase {// with TransformerFuzzing[ICETransformer] {
Add more testing cases for:
1. Duplicate features specified.
2. No features specified.
3. When setNumSamples is called, ICE mode returns correct number of rows.

2021-11-23 04:00 UTC, memoryz requested changes

2021-11-30 05:11 UTC, memoryz commented
Looks good now! Please abandon this PR and create a new PR to the upstream repo.

2023-10-02 23:45 UTC, closed without merging